# =============================================================================
# Typed inputs (WP-1.3)
# =============================================================================
# Grouped, typed replacements for the flat inputs. The defaults that matter live
# in the optional() attributes below. The old flat variables still work for one
# release: they default to null, take precedence when set, and raise the
# "deprecated_flat_inputs" warning (checks.tf) naming the replacement attribute.
# =============================================================================

variable "apim" {
  description = <<-EOT
    API Management settings.
      name                  null = generated by modules/naming.
      sku                   Developer | Premium | StandardV2 | PremiumV2.
      capacity              Scale units.
      vnet_mode             Developer/Premium: none | external | internal (classic VNet injection).
                            StandardV2/PremiumV2: integration (outbound VNet integration, always on).
                            null = external for classic SKUs, integration for v2 SKUs.
      private_endpoint      Inbound private endpoint (v2 SKUs).
      public_network_access Public inbound access (v2 SKUs).
  EOT
  type = object({
    name                  = optional(string)
    sku                   = optional(string, "StandardV2")
    capacity              = optional(number, 1)
    publisher_email       = optional(string, "admin@contoso.com")
    publisher_name        = optional(string, "AI Citadel Admin")
    vnet_mode             = optional(string)
    private_endpoint      = optional(bool, true)
    public_network_access = optional(bool, true)
  })
  default  = {}
  nullable = false

  validation {
    condition     = contains(["Developer", "Premium", "StandardV2", "PremiumV2"], var.apim.sku)
    error_message = "apim.sku must be Developer, Premium, StandardV2 or PremiumV2."
  }
  validation {
    condition = var.apim.vnet_mode == null || contains(lookup({
      Developer  = ["none", "external", "internal"]
      Premium    = ["none", "external", "internal"]
      StandardV2 = ["integration"]
      PremiumV2  = ["integration"]
    }, var.apim.sku, []), coalesce(var.apim.vnet_mode, "-"))
    error_message = "apim.vnet_mode isn't supported for this SKU: Developer/Premium take none, external or internal; StandardV2/PremiumV2 take integration."
  }
}

variable "network" {
  description = <<-EOT
    Virtual network and private DNS.
      mode            greenfield = create the VNet and subnets.
                      alz_spoke  = Azure Landing Zone spoke: the platform vends the VNet
                                   (resource_group_name + vnet_name, peered to the hub); this
                                   stack creates the subnets in it with NSGs and a UDR to
                                   hub_firewall_ip. Private DNS belongs to the platform.
                      byo        = look up an existing VNet and its subnets by name.
      vnet_name       null = generated by modules/naming (greenfield).
      address_space   Greenfield VNet address space.
      subnets         Name/prefix per subnet (prefixes are used in greenfield only).
      private_dns     resource_group_name + zone_ids empty = create the private DNS zones;
                      otherwise use the zone IDs supplied. zone_groups_managed_by_policy = true
                      leaves private endpoint DNS zone groups to Azure Policy (ALZ).
  EOT
  type = object({
    mode                = optional(string, "greenfield")
    resource_group_name = optional(string)
    # Default outbound internet access on the subnets this stack creates.
    # null = true for greenfield (no other egress path), false for alz_spoke
    # (egress through the hub firewall).
    default_outbound_access = optional(bool)
    # alz_spoke: private IP of the hub firewall (UDR next hop for 0.0.0.0/0).
    hub_firewall_ip = optional(string)
    vnet_name       = optional(string)
    address_space   = optional(string, "10.170.0.0/24")
    subnets = optional(object({
      apim = optional(object({
        name   = optional(string, "snet-citadel-apim")
        prefix = optional(string, "10.170.0.0/26")
      }), {})
      private_endpoint = optional(object({
        name   = optional(string, "snet-citadel-pe")
        prefix = optional(string, "10.170.0.64/26")
      }), {})
      logic_app = optional(object({
        name   = optional(string, "snet-citadel-functions")
        prefix = optional(string, "10.170.0.128/26")
      }), {})
      agent = optional(object({
        enabled = optional(bool, true)
        name    = optional(string, "snet-agents")
        prefix  = optional(string, "10.170.0.192/26")
      }), {})
      ase = optional(object({
        name   = optional(string, "snet-citadel-ase")
        prefix = optional(string, "10.170.1.0/24")
      }), {})
    }), {})
    private_dns = optional(object({
      resource_group_name = optional(string)
      zone_ids            = optional(map(string), {})
      # ALZ: Azure Policy (Deploy-Private-DNS-Zones) creates the private endpoint
      # DNS zone groups; Terraform must not create or remove them.
      zone_groups_managed_by_policy = optional(bool, false)
    }), {})
  })
  default  = {}
  nullable = false

  validation {
    condition     = contains(["greenfield", "alz_spoke", "byo"], var.network.mode)
    error_message = "network.mode must be greenfield, alz_spoke or byo."
  }
  validation {
    # Also covers the deprecated flat inputs (use_existing_vnet / existing_vnet_rg).
    condition     = !(var.use_existing_vnet != null ? var.use_existing_vnet : contains(["byo", "alz_spoke"], var.network.mode)) || (coalesce(var.existing_vnet_rg, var.network.resource_group_name, "-") != "-" && coalesce(var.vnet_name, var.network.vnet_name, "-") != "-")
    error_message = "network.mode = \"byo\" / \"alz_spoke\" needs network.resource_group_name and network.vnet_name (the existing VNet)."
  }
  validation {
    condition     = var.network.mode != "alz_spoke" || var.network.hub_firewall_ip != null
    error_message = "network.mode = \"alz_spoke\" needs network.hub_firewall_ip (the hub firewall's private IP)."
  }
}

variable "features" {
  description = "Optional gateway capabilities. semantic_cache deploys Azure Managed Redis as the APIM external cache; mcp_sample adds the sample MCP APIs."
  type = object({
    api_center            = optional(bool, true)
    api_center_onboarding = optional(bool, false)
    pii_redaction         = optional(bool, true)
    pii_anonymization     = optional(bool, true)
    content_safety        = optional(bool, true)
    semantic_cache        = optional(bool, false)
    unified_ai_api        = optional(bool, false)
    openai_realtime       = optional(bool, false)
    document_intelligence = optional(bool, false)
    ai_model_inference    = optional(bool, false)
    azure_ai_search       = optional(bool, false)
    embeddings_backend    = optional(bool, false)
    mcp_sample            = optional(bool, false)
  })
  default  = {}
  nullable = false
}

variable "usage_pipeline" {
  description = <<-EOT
    Usage ingestion pipeline (Event Hub -> Logic App -> Cosmos DB).
      logic_app.hosting  workflow_standard = WS plan with regional VNet integration (needs shared-key storage);
                         ase_v3 = Isolated v2 plan in an App Service Environment v3 (keyless storage).
      logic_app.sku      null = WS1 (workflow_standard) or I1v2 (ase_v3).
      ase                ASE v3 settings, used when logic_app.hosting = ase_v3.
  EOT
  type = object({
    eventhub = optional(object({
      capacity              = optional(number, 1)
      public_network_access = optional(string, "Enabled")
      disaster_recovery = optional(object({
        partner_namespace_id = string
        alias                = optional(string, "default")
      }))
    }), {})
    cosmos = optional(object({
      public_network_access = optional(string, "Disabled")
      local_auth_enabled    = optional(bool, false)
    }), {})
    logic_app = optional(object({
      hosting            = optional(string, "workflow_standard")
      sku                = optional(string)
      worker_count       = optional(number, 1)
      content_share_name = optional(string, "")
      code_deploy        = optional(bool, false)
      code_source_path   = optional(string, "")
    }), {})
    ase = optional(object({
      internal_load_balancing_mode = optional(string, "Web, Publishing")
      zone_redundant               = optional(bool, false)
      create_private_dns_zone      = optional(bool, true)
    }), {})
  })
  default  = {}
  nullable = false

  validation {
    condition     = contains(["workflow_standard", "ase_v3"], var.usage_pipeline.logic_app.hosting)
    error_message = "usage_pipeline.logic_app.hosting must be workflow_standard or ase_v3."
  }
  validation {
    condition = var.usage_pipeline.logic_app.sku == null || (
      var.usage_pipeline.logic_app.hosting == "ase_v3"
      ? can(regex("^I[1-6]m?v2$", coalesce(var.usage_pipeline.logic_app.sku, "-")))
      : can(regex("^WS[1-3]$", coalesce(var.usage_pipeline.logic_app.sku, "-")))
    )
    error_message = "usage_pipeline.logic_app.sku: ase_v3 needs an Isolated v2 SKU (I1v2..I6v2, I1mv2..I5mv2); workflow_standard needs WS1, WS2 or WS3."
  }
  validation {
    condition     = contains(["None", "Web, Publishing"], var.usage_pipeline.ase.internal_load_balancing_mode)
    error_message = "usage_pipeline.ase.internal_load_balancing_mode must be \"None\" or \"Web, Publishing\"."
  }
  validation {
    condition     = alltrue([for v in [var.usage_pipeline.eventhub.public_network_access, var.usage_pipeline.cosmos.public_network_access] : contains(["Enabled", "Disabled"], v)])
    error_message = "usage_pipeline.*.public_network_access must be Enabled or Disabled."
  }
}

variable "monitoring" {
  description = <<-EOT
    Log Analytics and Azure Monitor.
      log_analytics_workspace_id       null = create a workspace; set = use this (BYO / platform) workspace.
      log_analytics_subscription_id    Subscription of the BYO workspace when it differs from subscription_id.
      private_link_scope               Deploy an Azure Monitor Private Link Scope (AMPLS).
      app_insights_dashboards          Create the Application Insights dashboards.
  EOT
  type = object({
    log_analytics_workspace_id    = optional(string)
    log_analytics_subscription_id = optional(string)
    private_link_scope            = optional(bool, false)
    app_insights_dashboards       = optional(bool, true)
  })
  default  = {}
  nullable = false

  validation {
    # Also covers the deprecated flat inputs (use_existing_log_analytics / existing_log_analytics_id).
    condition = !(var.use_existing_log_analytics != null ? var.use_existing_log_analytics : var.monitoring.log_analytics_workspace_id != null) || can(regex(
      "(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/Microsoft\\.OperationalInsights/workspaces/[^/]+$",
      coalesce(var.existing_log_analytics_id, var.monitoring.log_analytics_workspace_id, "-")
    ))
    error_message = "monitoring.log_analytics_workspace_id must be a Log Analytics workspace resource ID (/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.OperationalInsights/workspaces/<name>)."
  }
}

# -----------------------------------------------------------------------------
# Effective configuration: a non-null deprecated flat input wins over the typed
# attribute. Downstream code reads only these locals.
# -----------------------------------------------------------------------------

locals {
  cfg_apim_sku    = coalesce(var.apim_sku, var.apim.sku)
  cfg_apim_is_v2  = contains(["StandardV2", "PremiumV2"], local.cfg_apim_sku)
  cfg_flat_vmodes = { External = "external", Internal = "internal", None = "none" }

  apim_cfg = {
    name            = coalesce(var.apim_service_name, var.apim.name, "-") == "-" ? "" : coalesce(var.apim_service_name, var.apim.name)
    sku             = local.cfg_apim_sku
    capacity        = coalesce(var.apim_sku_units, var.apim.capacity)
    publisher_email = coalesce(var.apim_publisher_email, var.apim.publisher_email)
    publisher_name  = coalesce(var.apim_publisher_name, var.apim.publisher_name)
    # v1 ignores the network type on v2 SKUs: they always use outbound integration.
    vnet_mode = local.cfg_apim_is_v2 ? "integration" : (
      var.apim_network_type != null ? local.cfg_flat_vmodes[var.apim_network_type] : coalesce(var.apim.vnet_mode, "external")
    )
    private_endpoint      = var.apim_v2_use_private_endpoint != null ? var.apim_v2_use_private_endpoint : var.apim.private_endpoint
    public_network_access = var.apim_v2_public_network_access != null ? var.apim_v2_public_network_access : var.apim.public_network_access
  }
  # Legacy network-type string still consumed by modules/apim and modules/networking.
  apim_network_type = lookup({ external = "External", internal = "Internal" }, local.apim_cfg.vnet_mode, "None")

  cfg_subnets = var.network.subnets
  network_cfg = {
    mode                = var.use_existing_vnet != null ? (var.use_existing_vnet ? "byo" : "greenfield") : var.network.mode
    byo                 = var.use_existing_vnet != null ? var.use_existing_vnet : var.network.mode == "byo"
    alz_spoke           = var.use_existing_vnet == null && var.network.mode == "alz_spoke"
    hub_firewall_ip     = var.network.hub_firewall_ip
    resource_group_name = coalesce(var.existing_vnet_rg, var.network.resource_group_name, "-") == "-" ? "" : coalesce(var.existing_vnet_rg, var.network.resource_group_name)
    vnet_name           = coalesce(var.vnet_name, var.network.vnet_name, "-") == "-" ? "" : coalesce(var.vnet_name, var.network.vnet_name)
    address_space       = coalesce(var.vnet_address_prefix, var.network.address_space)
    subnets = {
      apim = {
        name   = coalesce(var.apim_subnet_name, local.cfg_subnets.apim.name)
        prefix = coalesce(var.apim_subnet_prefix, local.cfg_subnets.apim.prefix)
      }
      private_endpoint = {
        name   = coalesce(var.private_endpoint_subnet_name, local.cfg_subnets.private_endpoint.name)
        prefix = coalesce(var.private_endpoint_subnet_prefix, local.cfg_subnets.private_endpoint.prefix)
      }
      logic_app = {
        name   = coalesce(var.logic_app_subnet_name, local.cfg_subnets.logic_app.name)
        prefix = coalesce(var.logic_app_subnet_prefix, local.cfg_subnets.logic_app.prefix)
      }
      agent = {
        enabled = var.enable_agent_subnet != null ? var.enable_agent_subnet : local.cfg_subnets.agent.enabled
        name    = coalesce(var.agent_subnet_name, local.cfg_subnets.agent.name)
        prefix  = coalesce(var.agent_subnet_prefix, local.cfg_subnets.agent.prefix)
      }
      ase = {
        name   = coalesce(var.ase_subnet_name, local.cfg_subnets.ase.name)
        prefix = coalesce(var.ase_subnet_prefix, local.cfg_subnets.ase.prefix)
      }
    }
    private_dns_resource_group_name = coalesce(var.dns_zone_rg, var.network.private_dns.resource_group_name, "-") == "-" ? "" : coalesce(var.dns_zone_rg, var.network.private_dns.resource_group_name)
    private_dns_zone_ids            = var.existing_private_dns_zones != null ? var.existing_private_dns_zones : var.network.private_dns.zone_ids
    # alz_spoke without zone IDs: Azure Policy (Deploy-Private-DNS-Zones) creates the zone groups.
    zone_groups_managed_by_policy = var.network.private_dns.zone_groups_managed_by_policy || (
      var.use_existing_vnet == null && var.network.mode == "alz_spoke" && length(var.network.private_dns.zone_ids) == 0
    )
    default_outbound_access = coalesce(var.network.default_outbound_access, !(var.use_existing_vnet == null && var.network.mode == "alz_spoke"))
  }

  cfg_flat_features = {
    api_center            = var.enable_api_center
    api_center_onboarding = var.enable_api_center_onboarding
    pii_redaction         = var.enable_pii_redaction
    pii_anonymization     = var.enable_pii_anonymization
    content_safety        = var.enable_content_safety
    semantic_cache        = var.enable_redis_cache
    unified_ai_api        = var.enable_unified_ai_api
    openai_realtime       = var.enable_openai_realtime
    document_intelligence = var.enable_document_intelligence
    ai_model_inference    = var.enable_ai_model_inference
    azure_ai_search       = var.enable_azure_ai_search
    embeddings_backend    = var.enable_embeddings_backend
    mcp_sample            = var.is_mcp_sample_deployed
  }
  features = {
    for k, v in var.features : k => lookup(local.cfg_flat_features, k, null) != null ? local.cfg_flat_features[k] : v
  }

  cfg_la_hosting = var.logic_app_hosting_model != null ? (
    var.logic_app_hosting_model == "AppServiceEnvironmentV3" ? "ase_v3" : "workflow_standard"
  ) : var.usage_pipeline.logic_app.hosting
  cfg_la = var.usage_pipeline.logic_app
  usage_cfg = {
    eventhub = {
      capacity              = coalesce(var.eventhub_capacity_units, var.usage_pipeline.eventhub.capacity)
      public_network_access = coalesce(var.eventhub_network_access, var.usage_pipeline.eventhub.public_network_access)
      disaster_recovery     = var.eventhub_disaster_recovery_config != null ? var.eventhub_disaster_recovery_config : var.usage_pipeline.eventhub.disaster_recovery
    }
    cosmos = {
      public_network_access = coalesce(var.cosmos_db_public_access, var.usage_pipeline.cosmos.public_network_access)
      local_auth_enabled    = var.cosmos_db_local_auth_enabled != null ? var.cosmos_db_local_auth_enabled : var.usage_pipeline.cosmos.local_auth_enabled
    }
    logic_app = {
      hosting = local.cfg_la_hosting
      # Legacy hosting-model string still consumed by modules/logic-app and modules/networking.
      hosting_model      = local.cfg_la_hosting == "ase_v3" ? "AppServiceEnvironmentV3" : "WorkflowStandard"
      ws_sku             = coalesce(var.logic_app_sku_size, local.cfg_la_hosting == "workflow_standard" ? local.cfg_la.sku : null, "WS1")
      ase_sku            = coalesce(var.logic_app_ase_sku_size, local.cfg_la_hosting == "ase_v3" ? local.cfg_la.sku : null, "I1v2")
      worker_count       = coalesce(var.logic_app_ase_worker_count, local.cfg_la.worker_count)
      content_share_name = var.logic_content_share_name != null ? var.logic_content_share_name : local.cfg_la.content_share_name
      code_deploy        = var.enable_logic_app_code_deploy != null ? var.enable_logic_app_code_deploy : local.cfg_la.code_deploy
      code_source_path   = var.logic_app_code_source_path != null ? var.logic_app_code_source_path : local.cfg_la.code_source_path
    }
    ase = {
      internal_load_balancing_mode = coalesce(var.ase_internal_load_balancing_mode, var.usage_pipeline.ase.internal_load_balancing_mode)
      zone_redundant               = var.ase_zone_redundant != null ? var.ase_zone_redundant : var.usage_pipeline.ase.zone_redundant
      create_private_dns_zone      = var.ase_create_private_dns_zone != null ? var.ase_create_private_dns_zone : var.usage_pipeline.ase.create_private_dns_zone
    }
  }

  cfg_la_workspace_id = coalesce(var.existing_log_analytics_id, var.monitoring.log_analytics_workspace_id, "-") == "-" ? "" : coalesce(var.existing_log_analytics_id, var.monitoring.log_analytics_workspace_id)
  monitoring_cfg = {
    byo_workspace             = var.use_existing_log_analytics != null ? var.use_existing_log_analytics : var.monitoring.log_analytics_workspace_id != null
    workspace_id              = local.cfg_la_workspace_id
    workspace_subscription_id = coalesce(var.existing_log_analytics_subscription_id, var.monitoring.log_analytics_subscription_id, "-") == "-" ? "" : coalesce(var.existing_log_analytics_subscription_id, var.monitoring.log_analytics_subscription_id)
    private_link_scope        = var.use_azure_monitor_private_link_scope != null ? var.use_azure_monitor_private_link_scope : var.monitoring.private_link_scope
    app_insights_dashboards   = var.create_app_insights_dashboards != null ? var.create_app_insights_dashboards : var.monitoring.app_insights_dashboards
  }

  # Deprecated flat input => replacement attribute, for the warning in checks.tf.
  deprecated_flat_inputs = {
    "apim_service_name -> apim.name"                                                      = var.apim_service_name != null
    "apim_sku -> apim.sku"                                                                = var.apim_sku != null
    "apim_sku_units -> apim.capacity"                                                     = var.apim_sku_units != null
    "apim_publisher_email -> apim.publisher_email"                                        = var.apim_publisher_email != null
    "apim_publisher_name -> apim.publisher_name"                                          = var.apim_publisher_name != null
    "apim_network_type -> apim.vnet_mode"                                                 = var.apim_network_type != null
    "apim_v2_use_private_endpoint -> apim.private_endpoint"                               = var.apim_v2_use_private_endpoint != null
    "apim_v2_public_network_access -> apim.public_network_access"                         = var.apim_v2_public_network_access != null
    "use_existing_vnet -> network.mode"                                                   = var.use_existing_vnet != null
    "existing_vnet_rg -> network.resource_group_name"                                     = var.existing_vnet_rg != null
    "vnet_name -> network.vnet_name"                                                      = var.vnet_name != null
    "vnet_address_prefix -> network.address_space"                                        = var.vnet_address_prefix != null
    "apim_subnet_name -> network.subnets.apim.name"                                       = var.apim_subnet_name != null
    "apim_subnet_prefix -> network.subnets.apim.prefix"                                   = var.apim_subnet_prefix != null
    "private_endpoint_subnet_name -> network.subnets.private_endpoint.name"               = var.private_endpoint_subnet_name != null
    "private_endpoint_subnet_prefix -> network.subnets.private_endpoint.prefix"           = var.private_endpoint_subnet_prefix != null
    "logic_app_subnet_name -> network.subnets.logic_app.name"                             = var.logic_app_subnet_name != null
    "logic_app_subnet_prefix -> network.subnets.logic_app.prefix"                         = var.logic_app_subnet_prefix != null
    "enable_agent_subnet -> network.subnets.agent.enabled"                                = var.enable_agent_subnet != null
    "agent_subnet_name -> network.subnets.agent.name"                                     = var.agent_subnet_name != null
    "agent_subnet_prefix -> network.subnets.agent.prefix"                                 = var.agent_subnet_prefix != null
    "ase_subnet_name -> network.subnets.ase.name"                                         = var.ase_subnet_name != null
    "ase_subnet_prefix -> network.subnets.ase.prefix"                                     = var.ase_subnet_prefix != null
    "dns_zone_rg -> network.private_dns.resource_group_name"                              = var.dns_zone_rg != null
    "existing_private_dns_zones -> network.private_dns.zone_ids"                          = var.existing_private_dns_zones != null
    "enable_api_center -> features.api_center"                                            = var.enable_api_center != null
    "enable_api_center_onboarding -> features.api_center_onboarding"                      = var.enable_api_center_onboarding != null
    "enable_pii_redaction -> features.pii_redaction"                                      = var.enable_pii_redaction != null
    "enable_pii_anonymization -> features.pii_anonymization"                              = var.enable_pii_anonymization != null
    "enable_content_safety -> features.content_safety"                                    = var.enable_content_safety != null
    "enable_redis_cache -> features.semantic_cache"                                       = var.enable_redis_cache != null
    "enable_unified_ai_api -> features.unified_ai_api"                                    = var.enable_unified_ai_api != null
    "enable_openai_realtime -> features.openai_realtime"                                  = var.enable_openai_realtime != null
    "enable_document_intelligence -> features.document_intelligence"                      = var.enable_document_intelligence != null
    "enable_ai_model_inference -> features.ai_model_inference"                            = var.enable_ai_model_inference != null
    "enable_azure_ai_search -> features.azure_ai_search"                                  = var.enable_azure_ai_search != null
    "enable_embeddings_backend -> features.embeddings_backend"                            = var.enable_embeddings_backend != null
    "is_mcp_sample_deployed -> features.mcp_sample"                                       = var.is_mcp_sample_deployed != null
    "eventhub_capacity_units -> usage_pipeline.eventhub.capacity"                         = var.eventhub_capacity_units != null
    "eventhub_network_access -> usage_pipeline.eventhub.public_network_access"            = var.eventhub_network_access != null
    "eventhub_disaster_recovery_config -> usage_pipeline.eventhub.disaster_recovery"      = var.eventhub_disaster_recovery_config != null
    "cosmos_db_public_access -> usage_pipeline.cosmos.public_network_access"              = var.cosmos_db_public_access != null
    "cosmos_db_local_auth_enabled -> usage_pipeline.cosmos.local_auth_enabled"            = var.cosmos_db_local_auth_enabled != null
    "logic_app_hosting_model -> usage_pipeline.logic_app.hosting"                         = var.logic_app_hosting_model != null
    "logic_app_sku_size -> usage_pipeline.logic_app.sku"                                  = var.logic_app_sku_size != null
    "logic_app_ase_sku_size -> usage_pipeline.logic_app.sku"                              = var.logic_app_ase_sku_size != null
    "logic_app_ase_worker_count -> usage_pipeline.logic_app.worker_count"                 = var.logic_app_ase_worker_count != null
    "logic_content_share_name -> usage_pipeline.logic_app.content_share_name"             = var.logic_content_share_name != null
    "enable_logic_app_code_deploy -> usage_pipeline.logic_app.code_deploy"                = var.enable_logic_app_code_deploy != null
    "logic_app_code_source_path -> usage_pipeline.logic_app.code_source_path"             = var.logic_app_code_source_path != null
    "ase_internal_load_balancing_mode -> usage_pipeline.ase.internal_load_balancing_mode" = var.ase_internal_load_balancing_mode != null
    "ase_zone_redundant -> usage_pipeline.ase.zone_redundant"                             = var.ase_zone_redundant != null
    "ase_create_private_dns_zone -> usage_pipeline.ase.create_private_dns_zone"           = var.ase_create_private_dns_zone != null
    "use_existing_log_analytics -> monitoring.log_analytics_workspace_id"                 = var.use_existing_log_analytics != null
    "existing_log_analytics_id -> monitoring.log_analytics_workspace_id"                  = var.existing_log_analytics_id != null
    "existing_log_analytics_subscription_id -> monitoring.log_analytics_subscription_id"  = var.existing_log_analytics_subscription_id != null
    "use_azure_monitor_private_link_scope -> monitoring.private_link_scope"               = var.use_azure_monitor_private_link_scope != null
    "create_app_insights_dashboards -> monitoring.app_insights_dashboards"                = var.create_app_insights_dashboards != null
  }
}
