# =============================================================================
# Typed inputs (WP-1.3)
# =============================================================================
# Grouped, typed inputs. The defaults live in the optional() attributes below;
# the locals at the end normalise them for the rest of the configuration.
# =============================================================================

variable "apim" {
  description = <<-EOT
    API Management settings.
      name                  null = generated by modules/naming.
      sku                   Developer | Premium | StandardV2 | PremiumV2.
      capacity              Scale units.
      vnet_mode             Developer/Premium: none | external | internal (classic VNet injection).
                            StandardV2/PremiumV2: integration (outbound VNet integration, always on).
                            null = external for classic SKUs, integration for v2 SKUs.
      private_endpoint      Inbound private endpoint (v2 SKUs).
      public_network_access Public inbound access (v2 SKUs).
  EOT
  type = object({
    name                  = optional(string)
    sku                   = optional(string, "StandardV2")
    capacity              = optional(number, 1)
    publisher_email       = optional(string, "admin@contoso.com")
    publisher_name        = optional(string, "AI Citadel Admin")
    vnet_mode             = optional(string)
    private_endpoint      = optional(bool, true)
    public_network_access = optional(bool, true)
  })
  default  = {}
  nullable = false

  validation {
    condition     = contains(["Developer", "Premium", "StandardV2", "PremiumV2"], var.apim.sku)
    error_message = "apim.sku must be Developer, Premium, StandardV2 or PremiumV2."
  }
  validation {
    condition = var.apim.vnet_mode == null || contains(lookup({
      Developer  = ["none", "external", "internal"]
      Premium    = ["none", "external", "internal"]
      StandardV2 = ["integration"]
      PremiumV2  = ["integration"]
    }, var.apim.sku, []), coalesce(var.apim.vnet_mode, "-"))
    error_message = "apim.vnet_mode isn't supported for this SKU: Developer/Premium take none, external or internal; StandardV2/PremiumV2 take integration."
  }
  validation {
    condition     = var.apim.sku != "Developer" || var.apim.capacity == 1
    error_message = "The Developer SKU can't scale out: apim.capacity must be 1."
  }
}

variable "network" {
  description = <<-EOT
    Virtual network and private DNS.
      mode            greenfield = create the VNet and subnets.
                      alz_spoke  = Azure Landing Zone spoke: the platform vends the VNet
                                   (resource_group_name + vnet_name, peered to the hub); this
                                   stack creates the subnets in it with NSGs and a UDR to
                                   hub_firewall_ip. Private DNS belongs to the platform.
                      byo        = look up an existing VNet and its subnets by name.
      vnet_name       null = generated by modules/naming (greenfield).
      address_space   Greenfield VNet address space.
      subnets         Name/prefix per subnet (prefixes are used in greenfield only).
      private_dns     resource_group_name + zone_ids empty = create the private DNS zones;
                      otherwise use the zone IDs supplied. zone_groups_managed_by_policy = true
                      leaves private endpoint DNS zone groups to Azure Policy (ALZ).
  EOT
  type = object({
    mode                = optional(string, "greenfield")
    resource_group_name = optional(string)
    # Default outbound internet access on the subnets this stack creates.
    # null = true for greenfield (no other egress path), false for alz_spoke
    # (egress through the hub firewall).
    default_outbound_access = optional(bool)
    # alz_spoke: private IP of the hub firewall (UDR next hop for 0.0.0.0/0).
    hub_firewall_ip = optional(string)
    vnet_name       = optional(string)
    address_space   = optional(string, "10.170.0.0/24")
    subnets = optional(object({
      apim = optional(object({
        name   = optional(string, "snet-citadel-apim")
        prefix = optional(string, "10.170.0.0/26")
      }), {})
      private_endpoint = optional(object({
        name   = optional(string, "snet-citadel-pe")
        prefix = optional(string, "10.170.0.64/26")
      }), {})
      logic_app = optional(object({
        name   = optional(string, "snet-citadel-functions")
        prefix = optional(string, "10.170.0.128/26")
      }), {})
      agent = optional(object({
        enabled = optional(bool, true)
        name    = optional(string, "snet-agents")
        prefix  = optional(string, "10.170.0.192/26")
      }), {})
      ase = optional(object({
        name   = optional(string, "snet-citadel-ase")
        prefix = optional(string, "10.170.1.0/24")
      }), {})
    }), {})
    private_dns = optional(object({
      resource_group_name = optional(string)
      zone_ids            = optional(map(string), {})
      # ALZ: Azure Policy (Deploy-Private-DNS-Zones) creates the private endpoint
      # DNS zone groups; Terraform must not create or remove them.
      zone_groups_managed_by_policy = optional(bool, false)
    }), {})
  })
  default  = {}
  nullable = false

  validation {
    condition     = contains(["greenfield", "alz_spoke", "byo"], var.network.mode)
    error_message = "network.mode must be greenfield, alz_spoke or byo."
  }
  validation {
    condition     = !contains(["byo", "alz_spoke"], var.network.mode) || (coalesce(var.network.resource_group_name, "-") != "-" && coalesce(var.network.vnet_name, "-") != "-")
    error_message = "network.mode = \"byo\" / \"alz_spoke\" needs network.resource_group_name and network.vnet_name (the existing VNet)."
  }
  validation {
    condition     = var.network.mode != "alz_spoke" || var.network.hub_firewall_ip != null
    error_message = "network.mode = \"alz_spoke\" needs network.hub_firewall_ip (the hub firewall's private IP)."
  }
}

variable "features" {
  description = "Optional gateway capabilities. semantic_cache deploys Azure Managed Redis as the APIM external cache; mcp_sample adds the sample MCP APIs."
  type = object({
    api_center            = optional(bool, true)
    api_center_onboarding = optional(bool, false)
    pii_redaction         = optional(bool, true)
    pii_anonymization     = optional(bool, true)
    content_safety        = optional(bool, true)
    semantic_cache        = optional(bool, false)
    unified_ai_api        = optional(bool, false)
    openai_realtime       = optional(bool, false)
    document_intelligence = optional(bool, false)
    ai_model_inference    = optional(bool, false)
    azure_ai_search       = optional(bool, false)
    embeddings_backend    = optional(bool, false)
    mcp_sample            = optional(bool, false)
  })
  default  = {}
  nullable = false
}

variable "usage_pipeline" {
  description = <<-EOT
    Usage ingestion pipeline (Event Hub -> Logic App -> Cosmos DB).
      logic_app.hosting  workflow_standard = WS plan with regional VNet integration (needs shared-key storage);
                         ase_v3 = Isolated v2 plan in an App Service Environment v3 (keyless storage).
      logic_app.sku      null = WS1 (workflow_standard) or I1v2 (ase_v3).
      ase                ASE v3 settings, used when logic_app.hosting = ase_v3.
  EOT
  type = object({
    eventhub = optional(object({
      capacity              = optional(number, 1)
      public_network_access = optional(string, "Enabled")
      disaster_recovery = optional(object({
        partner_namespace_id = string
        alias                = optional(string, "default")
      }))
    }), {})
    cosmos = optional(object({
      public_network_access = optional(string, "Disabled")
      local_auth_enabled    = optional(bool, false)
    }), {})
    logic_app = optional(object({
      hosting            = optional(string, "workflow_standard")
      sku                = optional(string)
      worker_count       = optional(number, 1)
      content_share_name = optional(string, "")
      code_deploy        = optional(bool, false)
      code_source_path   = optional(string, "")
    }), {})
    ase = optional(object({
      internal_load_balancing_mode = optional(string, "Web, Publishing")
      zone_redundant               = optional(bool, false)
      create_private_dns_zone      = optional(bool, true)
    }), {})
  })
  default  = {}
  nullable = false

  validation {
    condition     = contains(["workflow_standard", "ase_v3"], var.usage_pipeline.logic_app.hosting)
    error_message = "usage_pipeline.logic_app.hosting must be workflow_standard or ase_v3."
  }
  validation {
    condition = var.usage_pipeline.logic_app.sku == null || (
      var.usage_pipeline.logic_app.hosting == "ase_v3"
      ? can(regex("^I[1-6]m?v2$", coalesce(var.usage_pipeline.logic_app.sku, "-")))
      : can(regex("^WS[1-3]$", coalesce(var.usage_pipeline.logic_app.sku, "-")))
    )
    error_message = "usage_pipeline.logic_app.sku: ase_v3 needs an Isolated v2 SKU (I1v2..I6v2, I1mv2..I5mv2); workflow_standard needs WS1, WS2 or WS3."
  }
  validation {
    condition     = contains(["None", "Web, Publishing"], var.usage_pipeline.ase.internal_load_balancing_mode)
    error_message = "usage_pipeline.ase.internal_load_balancing_mode must be \"None\" or \"Web, Publishing\"."
  }
  validation {
    condition     = alltrue([for v in [var.usage_pipeline.eventhub.public_network_access, var.usage_pipeline.cosmos.public_network_access] : contains(["Enabled", "Disabled"], v)])
    error_message = "usage_pipeline.*.public_network_access must be Enabled or Disabled."
  }
}

variable "monitoring" {
  description = <<-EOT
    Log Analytics and Azure Monitor.
      log_analytics_workspace_id       null = create a workspace; set = use this (BYO / platform) workspace.
      log_analytics_subscription_id    Subscription of the BYO workspace when it differs from subscription_id.
      private_link_scope               Deploy an Azure Monitor Private Link Scope (AMPLS).
      app_insights_dashboards          Create the Application Insights dashboards.
  EOT
  type = object({
    log_analytics_workspace_id    = optional(string)
    log_analytics_subscription_id = optional(string)
    private_link_scope            = optional(bool, false)
    app_insights_dashboards       = optional(bool, true)
  })
  default  = {}
  nullable = false

  validation {
    condition = var.monitoring.log_analytics_workspace_id == null || can(regex(
      "(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/Microsoft\\.OperationalInsights/workspaces/[^/]+$",
      var.monitoring.log_analytics_workspace_id
    ))
    error_message = "monitoring.log_analytics_workspace_id must be a Log Analytics workspace resource ID (/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.OperationalInsights/workspaces/<name>)."
  }
}

# -----------------------------------------------------------------------------
# Effective configuration read by the rest of the root module.
# -----------------------------------------------------------------------------

locals {
  apim_cfg = {
    name            = coalesce(var.apim.name, "-") == "-" ? "" : var.apim.name
    sku             = var.apim.sku
    capacity        = var.apim.capacity
    publisher_email = var.apim.publisher_email
    publisher_name  = var.apim.publisher_name
    # v2 SKUs always use outbound VNet integration; classic SKUs default to external.
    vnet_mode             = contains(["StandardV2", "PremiumV2"], var.apim.sku) ? "integration" : coalesce(var.apim.vnet_mode, "external")
    private_endpoint      = var.apim.private_endpoint
    public_network_access = var.apim.public_network_access
  }
  # Network-type string consumed by modules/apim and modules/networking.
  apim_network_type = lookup({ external = "External", internal = "Internal" }, local.apim_cfg.vnet_mode, "None")

  network_cfg = {
    mode                = var.network.mode
    byo                 = var.network.mode == "byo"
    alz_spoke           = var.network.mode == "alz_spoke"
    hub_firewall_ip     = var.network.hub_firewall_ip
    resource_group_name = coalesce(var.network.resource_group_name, "-") == "-" ? "" : var.network.resource_group_name
    vnet_name           = coalesce(var.network.vnet_name, "-") == "-" ? "" : var.network.vnet_name
    address_space       = var.network.address_space
    subnets = {
      apim             = var.network.subnets.apim
      private_endpoint = var.network.subnets.private_endpoint
      logic_app        = var.network.subnets.logic_app
      agent            = var.network.subnets.agent
      ase              = var.network.subnets.ase
    }
    private_dns_resource_group_name = coalesce(var.network.private_dns.resource_group_name, "-") == "-" ? "" : var.network.private_dns.resource_group_name
    private_dns_zone_ids            = var.network.private_dns.zone_ids
    # alz_spoke without zone IDs: Azure Policy (Deploy-Private-DNS-Zones) creates the zone groups.
    zone_groups_managed_by_policy = var.network.private_dns.zone_groups_managed_by_policy || (var.network.mode == "alz_spoke" && length(var.network.private_dns.zone_ids) == 0)
    default_outbound_access       = coalesce(var.network.default_outbound_access, var.network.mode != "alz_spoke")
  }

  core_rollout = var.rollout_phase == "core"

  features = merge(var.features, local.core_rollout ? { mcp_sample = false, api_center_onboarding = false } : {})

  # Add-ons that are plain root inputs, forced off in the core rollout phase.
  enable_entra_id_setup          = var.enable_entra_id_setup && !local.core_rollout
  enable_foundry_apim_connection = var.enable_foundry_apim_connection && !local.core_rollout
  enable_jwt_auth                = var.enable_jwt_auth && !local.core_rollout

  usage_cfg = {
    eventhub = var.usage_pipeline.eventhub
    cosmos   = var.usage_pipeline.cosmos
    logic_app = {
      hosting = var.usage_pipeline.logic_app.hosting
      # Hosting-model string consumed by modules/logic-app.
      hosting_model      = var.usage_pipeline.logic_app.hosting == "ase_v3" ? "AppServiceEnvironmentV3" : "WorkflowStandard"
      ws_sku             = var.usage_pipeline.logic_app.hosting == "workflow_standard" ? coalesce(var.usage_pipeline.logic_app.sku, "WS1") : "WS1"
      ase_sku            = var.usage_pipeline.logic_app.hosting == "ase_v3" ? coalesce(var.usage_pipeline.logic_app.sku, "I1v2") : "I1v2"
      worker_count       = var.usage_pipeline.logic_app.worker_count
      content_share_name = var.usage_pipeline.logic_app.content_share_name
      code_deploy        = var.usage_pipeline.logic_app.code_deploy && !var.skip_logic_app_code_deploy
      code_source_path   = var.usage_pipeline.logic_app.code_source_path
    }
    ase = var.usage_pipeline.ase
  }

  monitoring_cfg = {
    byo_workspace             = var.monitoring.log_analytics_workspace_id != null
    workspace_id              = coalesce(var.monitoring.log_analytics_workspace_id, "-") == "-" ? "" : var.monitoring.log_analytics_workspace_id
    workspace_subscription_id = coalesce(var.monitoring.log_analytics_subscription_id, "-") == "-" ? "" : var.monitoring.log_analytics_subscription_id
    private_link_scope        = var.monitoring.private_link_scope
    app_insights_dashboards   = var.monitoring.app_insights_dashboards
  }
}
